# Generated by Django 4.0.5 on 2022-06-12 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('apellido', models.CharField(default=None, max_length=100)),
                ('edad', models.IntegerField(default=None)),
                ('direccion', models.CharField(default=None, max_length=100)),
                ('correo', models.CharField(default=None, max_length=50)),
                ('telefono', models.IntegerField(default=None)),
                ('receta', models.CharField(default=None, max_length=100)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('remedio', models.CharField(default=None, max_length=100)),
                ('horario', models.TimeField(default=None)),
            ],
        ),
    ]
